# Generated by Django 3.2.8 on 2021-11-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestQuestion',
        ),
    ]
