# Generated by Django 3.2.8 on 2021-11-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='total_no_of_questions',
            field=models.IntegerField(null=True),
        ),
    ]
