# Generated by Django 3.2.8 on 2021-11-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtc_exact_app', '0002_auto_20211105_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=200, null=True)),
                ('max_no_of_students', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
