# Generated by Django 3.2.8 on 2021-11-06 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtc_exact_app', '0004_batch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vtc_exact_app.vtcmodel'),
        ),
    ]
